NUMPY

THERE ARE DIFFEREENT OPERATIONS IN NUMPY
1.IMPORTING NUMPY
2.CREATING ARRAYS
3.ARRAY PROPERTIES
4.INDEXING & SLICING
5.RESHAPING
6.MATHEMATICAL OPERATIONS
7.MATRIX OPERATIONS
8.USEFUL FUNCTIONS
9.BOOLEAN FILTERING
10.COPY VS VIEW


CREATING ARRAYS

In [10]:


import numpy as np
a = np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])
zeors=np.zeros((2,3))
ones=np.ones((2,4))
rand=np.random.rand(3,3)


print(a,b,zeors,ones,rand)



[1 2 3] [[1 2 3]
 [4 5 6]] [[0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1. 1.]
 [1. 1. 1. 1.]] [[0.26895165 0.18471253 0.65636324]
 [0.48477338 0.88657263 0.88122578]
 [0.90941077 0.15764901 0.34667472]]


3.ARRAY PROPERTIES

In [18]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)#give the rows and columns in array
print(a.size)#gives the total elements present in array
print(a.ndim)#gives the dimension of array
print(a.dtype)#gives the data types of array

(2, 3)
6
2
int32


4.INDEXING AND SLICING

In [1]:
import numpy as np
a = np.array([10,20,30,40,50])
print(a[0])#prints the first element
print(a[-1])#prints the last elememt
print(a[1:4])#prints the slicing elements


10
50
[20 30 40]


In [8]:
import numpy as np
mat = np.array([[1,2,3],
               [4,5,6]])
print(mat[0,1])#prints the 0 column and 1st row
print(mat[:,1])#prints the entire column 1
print(mat[1,:])#prints the entire row 1


2
[2 5]
[4 5 6]


MATHEMATICAL OPERATIONS


In [16]:
import numpy as np
a = np.array([1,2,3])
b = np.array([10,20,30])
print(a+b)
print(a-b)
print(a*b)
print(a**b)
print(a**2)
            

[11 22 33]
[ -9 -18 -27]
[10 40 90]
[          1     1048576 -1010140999]
[1 4 9]


MATRIX OPERATIONS

In [28]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.dot(a,b))# prints dot product of matrix
print(np.transpose(a))#print the transpose of a
print(a @ b)           #prints the matrix multiplication

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[19 22]
 [43 50]]


FUNCITONS

In [29]:
import numpy as np
a = np.array([10,20,30,40])
print(a.sum()) #sum
print(a.mean())#mean
print(a.max())#max value
print(a.min())#min value
print(a.argmax())#index of max value
print(a.argmin())#index of min value

100
25.0
40
10
3
0


DOING CONDITIONS LIKE GREATER AND DIVISIBLE

In [31]:
import numpy as np
a = np.array([1,2,5,10,15,20])
filter1 = a[a>10] #prints as the condition follows
print(filter1)

filter2=a[a%2==0]
print(filter2)

[15 20]
[ 2 10 20]


COPY AND VIEW

In [33]:
import numpy as np
a = np.array([1,2,3])
view = a.view()
copy = a.copy()
a[0]=100
print(view)      # gives the view of changing attribute
print(copy)      #gives the copy of the given array

[100   2   3]
[1 2 3]
